# Generated by Django 4.1.7 on 2023-03-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='uname',
        ),
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
